### ISSUE TITLE
3.1.1 - release note tracking

### ISSUE THREAD

**Issue by cbarcl01** [pha4ge/Wastewater_Contextual_Data_Specification#7]
## Specification Changes:

| Field | Change |
| --- | --- |
| `INSDC sequence read accession` | new field | 
| `INSDC assembly accession` | new field  | 
| `genome sequence file name` | new field |
| `genome sequence file path` | new field  | 
| `proximal environmental site` | new field | 
| `environmental site` | new picklist IDs and defs | 
| `presampling activity` | new picklist IDs and defs | 
| `sequenced by laboratory name` | new field |
| `sample collected by laboratory name` | new field |
| `sample collector contact name` |	new field |

### Version Tracking:
Excel Template, Reference Guides, Curation SOP

x = 3 = new fields
y = 1 = new picklist IDs
z = 1 = new defs and changes to DH template

New Term SOP N/A unless indicated.

## Template To-Dos
- [x] Update picklist value labels/IDs/descriptions
  - [x] DataHarmonizer Template ([enums](<INSERT LINK TO EDITABLE DataHarmonizer TEMPLATE TAB>))
- [x] Update field labels/IDs/descriptions
  - [x] DataHarmonizer Template ([slots](<INSERT LINK TO EDITABLE GOOGLE DOC>))

**Comment by cbarcl01** [comment]
Field | ID | Change
--- | ---
INSDC sequence read accession | GENEPIO:0101203 | replaces previous fields 
genome sequence file name | GENEPIO:0101715 | new field
genome sequence file path | GENEPIO:0101716 | new field

**Comment by cbarcl01** [comment]
Field | ID | change
--- | --- | ---
proximal environmental site | GENEPIO:0101205 | new field

**Comment by cbarcl01** [comment]
New picklist terms

`environmental site` | ID
--- | ---
Influent pump station |           
Grit chamber |
Primary clarifer |
Aeration tank |
Secondary clarifer |
Commercial building | ENVO:01001222	
Office | ENVO:01001221
Restaurant | ENVO:01000934
Shopping mall | ENVO:03501207

**Comment by cbarcl01** [comment]
Subset reference guides to create a unique guide for each pathogen-specific template.

**Comment by cbarcl01** [comment]
Add mapping document.

**Comment by cbarcl01** [comment]
New picklist IDs 

 `presampling activity` | ID
--- | ---
Wastewater sludge removal | GENEPIO:0101201
Wastewater sludge dewatering | GENEPIO:0101202
Wastewater sludge drying | GENEPIO:0101718
Wastewater aerobic digestion | GENEPIO:0101199
Wastewater anaerobic digestion | GENEPIO:0101200
Wastewater screening process | GENEPIO:0101198
wastewater comminution process | GENEPIO:0101719

**Comment by cbarcl01** [comment]
Additional fields added to DataHarmonizer template **only** to allow for diagnostic testing of multiple targets (this will eventually be replaced by one to many functionality in the DH).  

- gene name 2
- gene name 2
- diagnostic target presence 2
- diagnostic measurement value 2
- diagnostic measurement unit 2
- diagnostic measurement method 2
- gene name 3
- gene name 3
- diagnostic target presence 3
- diagnostic measurement value 3
- diagnostic measurement unit 3
- diagnostic measurement method 3

**Comment by cbarcl01** [comment]
New fields

| field | ID |
| --- | --- |
| sequenced by laboratory name | GENEPIO:0100470 |
| sample collected by laboratory name | GENEPIO:0100428 |
| sample collector contact name | GENEPIO:0100432 |

**Comment by cbarcl01** [comment]
Updated to 3-1-1 to harmonise with DH release version.
